### ISSUE TITLE
readability issues 

### ISSUE THREAD

**Issue by snwng** [catppuccin/foot#12]
I recently had to reinstall foot, and after applying the theme i noticed that it looks a bit different and there is contrast issues when running some commands 

![Screenshot from 2024-05-05 00-39-29](https://github.com/catppuccin/foot/assets/127534631/ed28a2ec-cc10-4e0b-85aa-e1487df661b6)

![Screenshot from 2024-05-05 00-45-00](https://github.com/catppuccin/foot/assets/127534631/04ad0576-69a1-4266-aab0-497e4a8d822f)

**Comment by sachinchaudhary1808** [comment]
> I recently had to reinstall foot, and after applying the theme i noticed that it looks a bit different and there is contrast issues when running some commands
> 
> ![Screenshot from 2024-05-05 00-39-29](https://private-user-images.githubusercontent.com/127534631/327980398-ed28a2ec-cc10-4e0b-85aa-e1487df661b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTgzNzUsIm5iZiI6MTcxNTM5ODA3NSwicGF0aCI6Ii8xMjc1MzQ2MzEvMzI3OTgwMzk4LWVkMjhhMmVjLWNjMTAtNGUwYi04NWFhLWUxNDg3ZGY2NjFiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwMzI3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTQ3NjBmYzZkMWRhMjdlNzFjNmMwZGJlOTc4MWFhNzU4NDE2NmQ5ODQxYWU4ZTdiMGQxMGRhMzExZmY3YmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8dAVEFgettxKMPqw2UtDwzt60_NzhfRG_JdJH-gDz1c)
> 
> ![Screenshot from 2024-05-05 00-45-00](https://private-user-images.githubusercontent.com/127534631/327980506-04ad0576-69a1-4266-aab0-497e4a8d822f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTgzNzUsIm5iZiI6MTcxNTM5ODA3NSwicGF0aCI6Ii8xMjc1MzQ2MzEvMzI3OTgwNTA2LTA0YWQwNTc2LTY5YTEtNDI2Ni1hYWIwLTQ5N2U0YThkODIyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwMzI3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODVjMmVkMzlmODJhOTVhZWVlODA4NzQ3MmQyMWY0ZjQ1Y2RmOGI4NjA4NGZkZTFjYmZmMTk5YzVhNjg3MDA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PYnl5y6sf7hnAvJEhJbjdJvCwSRzuIDVEUkVCKf3z5Y)

same here on foot side

**Comment by sgoudham** [comment]
Could #11 be the cause of this?
cc: @nekowinston - I'm assuming you didn't run into this when adding the extra keys

**Comment by snwng** [comment]
yea didn't had any issues before that change

**Comment by snwng** [comment]
using this version fixes it : https://github.com/catppuccin/foot/tree/cfc55016e3d68a59622428e34d7b393447bbc501
